// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_jules/test/refresh_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i10;

import 'package:flutter/material.dart' as _i1;
import 'package:flutter_jules/models.dart' as _i8;
import 'package:flutter_jules/models/activity_log.dart' as _i19;
import 'package:flutter_jules/models/bulk_action.dart' as _i9;
import 'package:flutter_jules/models/refresh_schedule.dart' as _i7;
import 'package:flutter_jules/services/activity_provider.dart' as _i18;
import 'package:flutter_jules/services/auth_provider.dart' as _i16;
import 'package:flutter_jules/services/cache_service.dart' as _i12;
import 'package:flutter_jules/services/github_provider.dart' as _i13;
import 'package:flutter_jules/services/jules_client.dart' as _i3;
import 'package:flutter_jules/services/message_queue_provider.dart' as _i20;
import 'package:flutter_jules/services/notification_provider.dart' as _i14;
import 'package:flutter_jules/services/notification_service.dart' as _i17;
import 'package:flutter_jules/services/session_provider.dart' as _i11;
import 'package:flutter_jules/services/settings_provider.dart' as _i6;
import 'package:flutter_jules/services/source_provider.dart' as _i15;
import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i2;
import 'package:mockito/src/dummies.dart' as _i21;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGlobalKey_0<T extends _i1.State<_i1.StatefulWidget>>
    extends _i2.SmartFake implements _i1.GlobalKey<T> {
  _FakeGlobalKey_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJulesClient_1 extends _i2.SmartFake implements _i3.JulesClient {
  _FakeJulesClient_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFlutterLocalNotificationsPlugin_2 extends _i2.SmartFake
    implements _i4.FlutterLocalNotificationsPlugin {
  _FakeFlutterLocalNotificationsPlugin_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamController_3<T> extends _i2.SmartFake
    implements _i5.StreamController<T> {
  _FakeStreamController_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SettingsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsProvider extends _i2.Mock implements _i6.SettingsProvider {
  @override
  _i6.SessionRefreshPolicy get refreshOnOpen => (super.noSuchMethod(
        Invocation.getter(#refreshOnOpen),
        returnValue: _i6.SessionRefreshPolicy.none,
        returnValueForMissingStub: _i6.SessionRefreshPolicy.none,
      ) as _i6.SessionRefreshPolicy);

  @override
  _i6.SessionRefreshPolicy get refreshOnMessage => (super.noSuchMethod(
        Invocation.getter(#refreshOnMessage),
        returnValue: _i6.SessionRefreshPolicy.none,
        returnValueForMissingStub: _i6.SessionRefreshPolicy.none,
      ) as _i6.SessionRefreshPolicy);

  @override
  _i6.ListRefreshPolicy get refreshOnReturn => (super.noSuchMethod(
        Invocation.getter(#refreshOnReturn),
        returnValue: _i6.ListRefreshPolicy.none,
        returnValueForMissingStub: _i6.ListRefreshPolicy.none,
      ) as _i6.ListRefreshPolicy);

  @override
  _i6.ListRefreshPolicy get refreshOnCreate => (super.noSuchMethod(
        Invocation.getter(#refreshOnCreate),
        returnValue: _i6.ListRefreshPolicy.none,
        returnValueForMissingStub: _i6.ListRefreshPolicy.none,
      ) as _i6.ListRefreshPolicy);

  @override
  int get sessionPageSize => (super.noSuchMethod(
        Invocation.getter(#sessionPageSize),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  List<_i7.RefreshSchedule> get schedules => (super.noSuchMethod(
        Invocation.getter(#schedules),
        returnValue: <_i7.RefreshSchedule>[],
        returnValueForMissingStub: <_i7.RefreshSchedule>[],
      ) as List<_i7.RefreshSchedule>);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get notifyOnAttention => (super.noSuchMethod(
        Invocation.getter(#notifyOnAttention),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get notifyOnCompletion => (super.noSuchMethod(
        Invocation.getter(#notifyOnCompletion),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get notifyOnWatch => (super.noSuchMethod(
        Invocation.getter(#notifyOnWatch),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get notifyOnFailure => (super.noSuchMethod(
        Invocation.getter(#notifyOnFailure),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i6.FabVisibility get fabVisibility => (super.noSuchMethod(
        Invocation.getter(#fabVisibility),
        returnValue: _i6.FabVisibility.appBar,
        returnValueForMissingStub: _i6.FabVisibility.appBar,
      ) as _i6.FabVisibility);

  @override
  _i8.MessageSubmitAction get enterKeyAction => (super.noSuchMethod(
        Invocation.getter(#enterKeyAction),
        returnValue: _i8.MessageSubmitAction.addNewLine,
        returnValueForMissingStub: _i8.MessageSubmitAction.addNewLine,
      ) as _i8.MessageSubmitAction);

  @override
  _i8.MessageSubmitAction get shiftEnterKeyAction => (super.noSuchMethod(
        Invocation.getter(#shiftEnterKeyAction),
        returnValue: _i8.MessageSubmitAction.addNewLine,
        returnValueForMissingStub: _i8.MessageSubmitAction.addNewLine,
      ) as _i8.MessageSubmitAction);

  @override
  _i8.MessageSubmitAction get ctrlEnterKeyAction => (super.noSuchMethod(
        Invocation.getter(#ctrlEnterKeyAction),
        returnValue: _i8.MessageSubmitAction.addNewLine,
        returnValueForMissingStub: _i8.MessageSubmitAction.addNewLine,
      ) as _i8.MessageSubmitAction);

  @override
  _i8.MessageSubmitAction get ctrlShiftEnterKeyAction => (super.noSuchMethod(
        Invocation.getter(#ctrlShiftEnterKeyAction),
        returnValue: _i8.MessageSubmitAction.addNewLine,
        returnValueForMissingStub: _i8.MessageSubmitAction.addNewLine,
      ) as _i8.MessageSubmitAction);

  @override
  _i8.EscKeyAction get escKeyAction => (super.noSuchMethod(
        Invocation.getter(#escKeyAction),
        returnValue: _i8.EscKeyAction.savesDraftAndGoesBack,
        returnValueForMissingStub: _i8.EscKeyAction.savesDraftAndGoesBack,
      ) as _i8.EscKeyAction);

  @override
  List<_i9.BulkActionStep> get lastBulkActions => (super.noSuchMethod(
        Invocation.getter(#lastBulkActions),
        returnValue: <_i9.BulkActionStep>[],
        returnValueForMissingStub: <_i9.BulkActionStep>[],
      ) as List<_i9.BulkActionStep>);

  @override
  int get lastBulkParallelQueries => (super.noSuchMethod(
        Invocation.getter(#lastBulkParallelQueries),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  int get lastBulkWaitBetweenSeconds => (super.noSuchMethod(
        Invocation.getter(#lastBulkWaitBetweenSeconds),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  int get lastBulkOffset => (super.noSuchMethod(
        Invocation.getter(#lastBulkOffset),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool get lastBulkRandomize => (super.noSuchMethod(
        Invocation.getter(#lastBulkRandomize),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get lastBulkStopOnError => (super.noSuchMethod(
        Invocation.getter(#lastBulkStopOnError),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addSchedule(_i7.RefreshSchedule? schedule) =>
      (super.noSuchMethod(
        Invocation.method(
          #addSchedule,
          [schedule],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateSchedule(_i7.RefreshSchedule? schedule) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSchedule,
          [schedule],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteSchedule(String? scheduleId) => (super.noSuchMethod(
        Invocation.method(
          #deleteSchedule,
          [scheduleId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setSessionPageSize(int? size) => (super.noSuchMethod(
        Invocation.method(
          #setSessionPageSize,
          [size],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setRefreshOnOpen(_i6.SessionRefreshPolicy? policy) =>
      (super.noSuchMethod(
        Invocation.method(
          #setRefreshOnOpen,
          [policy],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setRefreshOnMessage(_i6.SessionRefreshPolicy? policy) =>
      (super.noSuchMethod(
        Invocation.method(
          #setRefreshOnMessage,
          [policy],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setRefreshOnReturn(_i6.ListRefreshPolicy? policy) =>
      (super.noSuchMethod(
        Invocation.method(
          #setRefreshOnReturn,
          [policy],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setRefreshOnCreate(_i6.ListRefreshPolicy? policy) =>
      (super.noSuchMethod(
        Invocation.method(
          #setRefreshOnCreate,
          [policy],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setNotifyOnAttention(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setNotifyOnAttention,
          [value],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setNotifyOnCompletion(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setNotifyOnCompletion,
          [value],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setNotifyOnWatch(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setNotifyOnWatch,
          [value],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setNotifyOnFailure(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setNotifyOnFailure,
          [value],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setFabVisibility(_i6.FabVisibility? visibility) =>
      (super.noSuchMethod(
        Invocation.method(
          #setFabVisibility,
          [visibility],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setEnterKeyAction(_i8.MessageSubmitAction? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #setEnterKeyAction,
          [action],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setShiftEnterKeyAction(_i8.MessageSubmitAction? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #setShiftEnterKeyAction,
          [action],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setCtrlEnterKeyAction(_i8.MessageSubmitAction? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCtrlEnterKeyAction,
          [action],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setCtrlShiftEnterKeyAction(
          _i8.MessageSubmitAction? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCtrlShiftEnterKeyAction,
          [action],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setEscKeyAction(_i8.EscKeyAction? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #setEscKeyAction,
          [action],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setLastFilter(_i8.FilterElement? filter) =>
      (super.noSuchMethod(
        Invocation.method(
          #setLastFilter,
          [filter],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveBulkActionConfig({
    required List<_i9.BulkActionStep>? actions,
    required int? parallelQueries,
    required int? waitBetweenSeconds,
    required int? limit,
    required int? offset,
    required bool? randomize,
    required bool? stopOnError,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveBulkActionConfig,
          [],
          {
            #actions: actions,
            #parallelQueries: parallelQueries,
            #waitBetweenSeconds: waitBetweenSeconds,
            #limit: limit,
            #offset: offset,
            #randomize: randomize,
            #stopOnError: stopOnError,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SessionProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionProvider extends _i2.Mock implements _i11.SessionProvider {
  @override
  _i1.GlobalKey<_i1.ScaffoldMessengerState> get scaffoldKey =>
      (super.noSuchMethod(
        Invocation.getter(#scaffoldKey),
        returnValue: _FakeGlobalKey_0<_i1.ScaffoldMessengerState>(
          this,
          Invocation.getter(#scaffoldKey),
        ),
        returnValueForMissingStub: _FakeGlobalKey_0<_i1.ScaffoldMessengerState>(
          this,
          Invocation.getter(#scaffoldKey),
        ),
      ) as _i1.GlobalKey<_i1.ScaffoldMessengerState>);

  @override
  List<_i12.CachedItem<_i8.Session>> get items => (super.noSuchMethod(
        Invocation.getter(#items),
        returnValue: <_i12.CachedItem<_i8.Session>>[],
        returnValueForMissingStub: <_i12.CachedItem<_i8.Session>>[],
      ) as List<_i12.CachedItem<_i8.Session>>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void setCacheService(_i12.CacheService? service) => super.noSuchMethod(
        Invocation.method(
          #setCacheService,
          [service],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setGithubProvider(_i13.GithubProvider? service) => super.noSuchMethod(
        Invocation.method(
          #setGithubProvider,
          [service],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setNotificationProvider(_i14.NotificationProvider? service) =>
      super.noSuchMethod(
        Invocation.method(
          #setNotificationProvider,
          [service],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> fetchSessions(
    _i3.JulesClient? client, {
    bool? force = false,
    bool? shallow = true,
    int? pageSize = 100,
    String? authToken,
    void Function(String)? onRefreshFallback,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchSessions,
          [client],
          {
            #force: force,
            #shallow: shallow,
            #pageSize: pageSize,
            #authToken: authToken,
            #onRefreshFallback: onRefreshFallback,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateSession(
    _i8.Session? session, {
    String? authToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSession,
          [session],
          {#authToken: authToken},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> refreshSession(
    _i3.JulesClient? client,
    String? sessionName, {
    String? authToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshSession,
          [
            client,
            sessionName,
          ],
          {#authToken: authToken},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> refreshDirtySessions(
    _i3.JulesClient? client, {
    required String? authToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshDirtySessions,
          [client],
          {#authToken: authToken},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> refreshWatchedSessions(
    _i3.JulesClient? client, {
    required String? authToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshWatchedSessions,
          [client],
          {#authToken: authToken},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> toggleWatch(
    String? sessionId,
    String? authToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleWatch,
          [
            sessionId,
            authToken,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> toggleHidden(
    String? sessionId,
    String? authToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleHidden,
          [
            sessionId,
            authToken,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addPendingMessage(
    String? sessionId,
    String? content,
    String? authToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addPendingMessage,
          [
            sessionId,
            content,
            authToken,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removePendingMessage(
    String? sessionId,
    String? pendingId,
    String? authToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removePendingMessage,
          [
            sessionId,
            pendingId,
            authToken,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> markAsPendingUpdate(
    String? sessionId,
    String? authToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsPendingUpdate,
          [
            sessionId,
            authToken,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> markAsRead(
    String? sessionId,
    String? authToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsRead,
          [
            sessionId,
            authToken,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> markAsUnread(
    String? sessionId,
    String? authToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsUnread,
          [
            sessionId,
            authToken,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> markPrAsOpened(
    String? sessionId,
    String? authToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markPrAsOpened,
          [
            sessionId,
            authToken,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> refreshGitStatus(
    String? sessionId,
    String? authToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshGitStatus,
          [
            sessionId,
            authToken,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateSessionTags(
    _i8.Session? session,
    List<String>? tags,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSessionTags,
          [
            session,
            tags,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> refreshSessionsForSource(
    _i3.JulesClient? client,
    String? sourceName, {
    required String? authToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshSessionsForSource,
          [
            client,
            sourceName,
          ],
          {#authToken: authToken},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SourceProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSourceProvider extends _i2.Mock implements _i15.SourceProvider {
  @override
  List<_i12.CachedItem<_i8.Source>> get items => (super.noSuchMethod(
        Invocation.getter(#items),
        returnValue: <_i12.CachedItem<_i8.Source>>[],
        returnValueForMissingStub: <_i12.CachedItem<_i8.Source>>[],
      ) as List<_i12.CachedItem<_i8.Source>>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void setCacheService(_i12.CacheService? service) => super.noSuchMethod(
        Invocation.method(
          #setCacheService,
          [service],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> fetchSources(
    _i3.JulesClient? client, {
    bool? force = false,
    String? authToken,
    _i13.GithubProvider? githubProvider,
    _i11.SessionProvider? sessionProvider,
    dynamic Function(int)? onProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchSources,
          [client],
          {
            #force: force,
            #authToken: authToken,
            #githubProvider: githubProvider,
            #sessionProvider: sessionProvider,
            #onProgress: onProgress,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> ensureSourceAvailable(
    _i3.JulesClient? client,
    String? sourceName, {
    String? authToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #ensureSourceAvailable,
          [
            client,
            sourceName,
          ],
          {#authToken: authToken},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> refreshSource(
    _i8.Source? sourceToRefresh, {
    String? authToken,
    _i13.GithubProvider? githubProvider,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshSource,
          [sourceToRefresh],
          {
            #authToken: authToken,
            #githubProvider: githubProvider,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i2.Mock implements _i16.AuthProvider {
  @override
  _i16.TokenType get tokenType => (super.noSuchMethod(
        Invocation.getter(#tokenType),
        returnValue: _i16.TokenType.apiKey,
        returnValueForMissingStub: _i16.TokenType.apiKey,
      ) as _i16.TokenType);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.JulesClient get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeJulesClient_1(
          this,
          Invocation.getter(#client),
        ),
        returnValueForMissingStub: _FakeJulesClient_1(
          this,
          Invocation.getter(#client),
        ),
      ) as _i3.JulesClient);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.Future<void> setToken(
    String? token,
    _i16.TokenType? type,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setToken,
          [
            token,
            type,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i2.Mock
    implements _i17.NotificationService {
  @override
  _i4.FlutterLocalNotificationsPlugin get flutterLocalNotificationsPlugin =>
      (super.noSuchMethod(
        Invocation.getter(#flutterLocalNotificationsPlugin),
        returnValue: _FakeFlutterLocalNotificationsPlugin_2(
          this,
          Invocation.getter(#flutterLocalNotificationsPlugin),
        ),
        returnValueForMissingStub: _FakeFlutterLocalNotificationsPlugin_2(
          this,
          Invocation.getter(#flutterLocalNotificationsPlugin),
        ),
      ) as _i4.FlutterLocalNotificationsPlugin);

  @override
  _i5.StreamController<_i4.NotificationResponse> get onNotificationResponse =>
      (super.noSuchMethod(
        Invocation.getter(#onNotificationResponse),
        returnValue: _FakeStreamController_3<_i4.NotificationResponse>(
          this,
          Invocation.getter(#onNotificationResponse),
        ),
        returnValueForMissingStub:
            _FakeStreamController_3<_i4.NotificationResponse>(
          this,
          Invocation.getter(#onNotificationResponse),
        ),
      ) as _i5.StreamController<_i4.NotificationResponse>);

  @override
  _i5.Stream<_i4.NotificationResponse> get onNotificationResponseStream =>
      (super.noSuchMethod(
        Invocation.getter(#onNotificationResponseStream),
        returnValue: _i5.Stream<_i4.NotificationResponse>.empty(),
        returnValueForMissingStub: _i5.Stream<_i4.NotificationResponse>.empty(),
      ) as _i5.Stream<_i4.NotificationResponse>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> showNotification(
    String? title,
    String? body, {
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showNotification,
          [
            title,
            body,
          ],
          {#payload: payload},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [ActivityProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockActivityProvider extends _i2.Mock implements _i18.ActivityProvider {
  @override
  List<_i19.ActivityLog> get logs => (super.noSuchMethod(
        Invocation.getter(#logs),
        returnValue: <_i19.ActivityLog>[],
        returnValueForMissingStub: <_i19.ActivityLog>[],
      ) as List<_i19.ActivityLog>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void addLog(String? message) => super.noSuchMethod(
        Invocation.method(
          #addLog,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MessageQueueProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageQueueProvider extends _i2.Mock
    implements _i20.MessageQueueProvider {
  @override
  List<_i8.QueuedMessage> get queue => (super.noSuchMethod(
        Invocation.getter(#queue),
        returnValue: <_i8.QueuedMessage>[],
        returnValueForMissingStub: <_i8.QueuedMessage>[],
      ) as List<_i8.QueuedMessage>);

  @override
  bool get isOffline => (super.noSuchMethod(
        Invocation.getter(#isOffline),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isConnecting => (super.noSuchMethod(
        Invocation.getter(#isConnecting),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void setCacheService(
    _i12.CacheService? service,
    String? token,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setCacheService,
          [
            service,
            token,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setOffline(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setOffline,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> resyncQueue() => (super.noSuchMethod(
        Invocation.method(
          #resyncQueue,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  String addMessage(
    String? sessionId,
    String? content, {
    String? reason,
    bool? isDraft = false,
    String? requestId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMessage,
          [
            sessionId,
            content,
          ],
          {
            #reason: reason,
            #isDraft: isDraft,
            #requestId: requestId,
          },
        ),
        returnValue: _i21.dummyValue<String>(
          this,
          Invocation.method(
            #addMessage,
            [
              sessionId,
              content,
            ],
            {
              #reason: reason,
              #isDraft: isDraft,
              #requestId: requestId,
            },
          ),
        ),
        returnValueForMissingStub: _i21.dummyValue<String>(
          this,
          Invocation.method(
            #addMessage,
            [
              sessionId,
              content,
            ],
            {
              #reason: reason,
              #isDraft: isDraft,
              #requestId: requestId,
            },
          ),
        ),
      ) as String);

  @override
  String addCreateSessionRequest(
    _i8.Session? session, {
    String? reason,
    bool? isDraft = false,
    String? requestId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCreateSessionRequest,
          [session],
          {
            #reason: reason,
            #isDraft: isDraft,
            #requestId: requestId,
          },
        ),
        returnValue: _i21.dummyValue<String>(
          this,
          Invocation.method(
            #addCreateSessionRequest,
            [session],
            {
              #reason: reason,
              #isDraft: isDraft,
              #requestId: requestId,
            },
          ),
        ),
        returnValueForMissingStub: _i21.dummyValue<String>(
          this,
          Invocation.method(
            #addCreateSessionRequest,
            [session],
            {
              #reason: reason,
              #isDraft: isDraft,
              #requestId: requestId,
            },
          ),
        ),
      ) as String);

  @override
  void updateMessage(
    String? id,
    String? newContent,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateMessage,
          [
            id,
            newContent,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateCreateSessionRequest(
    String? id,
    _i8.Session? session, {
    bool? isDraft,
    String? reason,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #updateCreateSessionRequest,
          [
            id,
            session,
          ],
          {
            #isDraft: isDraft,
            #reason: reason,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void deleteMessage(String? id) => super.noSuchMethod(
        Invocation.method(
          #deleteMessage,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void saveDraft(
    String? sessionId,
    String? content,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #saveDraft,
          [
            sessionId,
            content,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i8.QueuedMessage> getDrafts(String? sessionId) => (super.noSuchMethod(
        Invocation.method(
          #getDrafts,
          [sessionId],
        ),
        returnValue: <_i8.QueuedMessage>[],
        returnValueForMissingStub: <_i8.QueuedMessage>[],
      ) as List<_i8.QueuedMessage>);

  @override
  _i5.Future<bool> goOnline(_i3.JulesClient? client) => (super.noSuchMethod(
        Invocation.method(
          #goOnline,
          [client],
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> sendQueue(
    _i3.JulesClient? client, {
    dynamic Function(String)? onMessageSent,
    dynamic Function(_i8.Session)? onSessionCreated,
    dynamic Function(
      String,
      Object,
    )? onError,
    int? limit = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendQueue,
          [client],
          {
            #onMessageSent: onMessageSent,
            #onSessionCreated: onSessionCreated,
            #onError: onError,
            #limit: limit,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> importLegacyQueue(String? filePath) => (super.noSuchMethod(
        Invocation.method(
          #importLegacyQueue,
          [filePath],
        ),
        returnValue: _i5.Future<String>.value(_i21.dummyValue<String>(
          this,
          Invocation.method(
            #importLegacyQueue,
            [filePath],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<String>.value(_i21.dummyValue<String>(
          this,
          Invocation.method(
            #importLegacyQueue,
            [filePath],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String?> getQueuePathForSessionId(String? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQueuePathForSessionId,
          [sessionId],
        ),
        returnValue: _i5.Future<String?>.value(),
        returnValueForMissingStub: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
