enum AutomationMode {
  AUTOMATION_MODE_UNSPECIFIED,
  AUTO_CREATE_PR,
}

enum SessionState {
  STATE_UNSPECIFIED,
  QUEUED,
  PLANNING,
  AWAITING_PLAN_APPROVAL,
  AWAITING_USER_FEEDBACK,
  IN_PROGRESS,
  PAUSED,
  FAILED,
  COMPLETED,
}
